# pyproject.toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "test",
]
pythonpath = [
  "."
]


[tool.ruff]
# Assume Python 3.12
target-version = "py39"

[tool.ruff.lint]
select = ["ALL"]